### ISSUE TITLE
Git ignore question

### ISSUE THREAD

**Issue by jasper-oh** [YVR-Hackathon-ICN-Hacks/YVR-ICNHacks#7]
Do we need Android and iOS folders in this repo? 

Since React Native automatically generates Android and iOS build projects for us, and I believe there's nothing we need to directly modify or change, is there a reason why the Android and iOS folders should exist in the GitHub repo? If they're not necessary, I'm curious if we can proceed with including them in the Git ignore file.

**Comment by gdcho** [comment]
Good question. If we're discussing whether or not it's visible to us while working on the code, it doesn't matter because we can each generate it for ourselves. However, if we are planning to move to development, I believe during the build process, it generates the folders and code to its latest build, which would require the folders.

**Comment by jasper-oh** [comment]
Currently, as we are undergoing various R&D processes, it is expected that various Pod or Gradle configuration errors may arise. Indeed, an unexpected Pod related issue occurred, and after deleting the iOS folder and rebuilding, the error disappeared.

Therefore, if possible, during the current R&D process, it might be advisable to include the android and iOS folders in the git ignore to avoid uploading individual builds. Later, once the topic is finalized and faster builds are desired, I think we can consider adding them back just like you mention

**Comment by gdcho** [comment]
Ok, sounds good to me
